@startuml node

package ai {
  class Node {
    - Node parent
    - int col
    - int row
    - int gCost
    - int hCost
    - int fCost
    - boolean solid
    - boolean open
    - boolean checked

    + Node(int, int)
  }
}

@enduml
